name: Deploy GitHub Pages

on:
  push:
    branches: [master, ci-modificaitons]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/git
            ~/.cargo/registry
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          
        # Build Rust
      - name: Install Rust Dependencies
        run: |
          cargo install wasm-pack || true \
            && rustup target add wasm32-unknown-unknown
      - name: Build the Rust WASM
        run: wasm-pack build

        # Get NPM dependencies
      - name: Install NPM Dependencies
        run: cd ./docs && npm install && npm run build

        # Build tar file
      - name: Create webpack
        run: cd ./docs && webpack

        # Upload the html artifact
      - name: Upload  artifact
        uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: ./docs/dist
  deploy:
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
            artifact_name: github-pages
