name: Deploy GitHub Pages

on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/git
            ~/.cargo/registry
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          
        # Build Rust
      - name: Install Rust Dependencies
        run: |
          cargo install wasm-pack || true \
            && rustup target add wasm32-unknown-unknown
      - name: Build the Rust WASM
        run: wasm-pack build

        # Upload the html artifact
      - name: Upload  artifact
        uses: actions/upload-page-artifact@v1
        with:
          name: webapp
          path: |
            ./docs/*.*
            ./pkg/

        # Get NPM dependencies
      - name: Install NPM Dependencies
        run: cd ./docs && npm install && npm run build
  deploy:
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
            artifact_name: webapp
