name: Deploy GitHub Pages
env:
  HTMLPATH: './docs'

on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/git
            ~/.cargo/registry
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Rust Dependencies
        run: |
          cargo install wasm-pack || true \
            && rustup target add wasm32-unknown-unknown

      - name: Build the Rust WASM
        run: wasm-pack build
        
      - name: Install NPM Dependencies
        run: cd $HTMLPATH && npm install

  deploy:
    needs: build

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Pages
        uses: actions/configure-pages@v3

        # Upload the html artifact
      - name: Upload docs artifact
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: $HTMLPATH

        # Upload the wasm artifact
      - name: Upload wasm-pack pkg artifact
        uses: actions/upload-artifact@v2
        with:
          name: wasm-pack-pkg
          path: './pkg'
          
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
